language: go

go:
  - 1.6
  - tip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install qemu-kvm
  - export PATH=/home/travis/gopath/bin:$PATH
  - REPO_NAME=`basename $PWD`; SRC_DIR=`dirname $PWD`; DEST_DIR="`dirname $SRC_DIR`/cloudius-systems"
  - if [[ "$SRC_DIR" != "$DEST_DIR" ]]; then mv "$SRC_DIR" "$DEST_DIR"; cd ../../cloudius-systems/$REPO_NAME; export TRAVIS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/$REPO_NAME; fi

install:
  - ./install
